// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnplUkLLu3pSX8-vc4Jg7ZYZEw9zh0sWM',
    appId: '1:872966184512:web:a38c1d2b6fcf18b3c889a5',
    messagingSenderId: '872966184512',
    projectId: 'pingpi',
    authDomain: 'pingpi.firebaseapp.com',
    storageBucket: 'pingpi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdUZqEo49ZNglCuzChcg1jaMopBPXFkdQ',
    appId: '1:872966184512:android:1ece45ee6b8e4a0ec889a5',
    messagingSenderId: '872966184512',
    projectId: 'pingpi',
    storageBucket: 'pingpi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnplUkLLu3pSX8-vc4Jg7ZYZEw9zh0sWM',
    appId: '1:872966184512:web:3cb3b28eb810ac4fc889a5',
    messagingSenderId: '872966184512',
    projectId: 'pingpi',
    authDomain: 'pingpi.firebaseapp.com',
    storageBucket: 'pingpi.firebasestorage.app',
  );
}
